//NaN - Not a number ; it is number generated by js runtime during runtime incase any 
//numerical compuation fails

//if you get NaN , that is bug, you have to fix it.

//NaN - when you do computation against undefined values


var a
var b = 10
var c = a * b
console.log(`a ${a} b ${b} c ${c}`)

//
var x = "10"
// var x = "10"
var y = 20
var z = x + y // +  is used for concation and numerical addition
// //js does automatic type cast
// var r = x * y
//js does automatic type cast
//var r = x * parseInt(y)
var r = x * parseFloat(y)
console.log(z, r)

var doc = `
  <html>
  </html>
`